harden scripts

diff --git a/templates/knockd_open.j2 b/templates/knockd_open.j2
--- a/templates/knockd_open.j2
+++ b/templates/knockd_open.j2
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
-set -e
 HOST_IP=$1
 
+if [[ ${HOST_IP} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+  echo "$0: ${HOST_IP} is valid"
+else
+  echo "$0: ${HOST_IP} is invalid"
+fi
+
 {% for port,proto in secure_ports %}
-if /sbin/iptables -C INPUT -s "${HOST_IP}" -p {{ proto }} --dport {{ port }} -j ACCEPT
+if ! /sbin/iptables -C INPUT -s "${HOST_IP}" -p {{ proto }} --dport {{ port }} -j ACCEPT
 then
     /sbin/iptables -I INPUT 1 -s "${HOST_IP}" -p {{ proto }} --dport {{ port }} -j ACCEPT
 fi
